const Api = {
  RunningApi: [
    {
      id: 1,
      img: "/public/shopcard/img1.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 2,
      img: "/public/shopcard/img2.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 3,
      img: "/public/shopcard/img3.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 4,
      img: "/public/shopcard/img4.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 5,
      img: "/public/shopcard/img5.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 6,
      img: "/public/shopcard/img6.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 7,
      img: "/public/shopcard/img7.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 8,
      img: "/public/shopcard/img8.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 9,
      img: "/public/shopcard/img9.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 10,
      img: "/public/shopcard/img10.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 11,
      img: "/public/shopcard/img11.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 12,
      img: "/public/shopcard/img12.jpg",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
  ],
  SportswareApi: [
    {
      id: 1,
      img: "/public/sportware/img1.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 2,
      img: "/public/sportware/img2.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 3,
      img: "/public/sportware/img3.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 4,
      img: "/public/sportware/img4.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 5,
      img: "/public/sportware/img5.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 6,
      img: "/public/sportware/img6.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 7,
      img: "/public/sportware/img7.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 8,
      img: "/public/sportware/img8.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 9,
      img: "/public/sportware/img9.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 10,
      img: "/public/sportware/img10.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
    {
      id: 11,
      img: "/public/sportware/img11.avif",
      discount: -4.6,
      price: "3,499",
      salesPrice: "1,299",
      title: "HYPERON 1.0 SHOES",
      star: 0,
    },
  ],
};

export default Api;

// format of api
// {
//     id : 1,
//     img : "/public/shopcard/img1.jpg",
//     discount : -4.6,
//     price : "3,499",
//     salesPrice : "1,299",
//     title : "HYPERON 1.0 SHOES",
//     star : 0
// }
